matrix:
  include:
    - language: php
      before_script:
        - cd api
      sudo: false
      services:
        - postgresql
      cache:
        directories:
          - $HOME/.composer/cache/files
      matrix:
        fast_finish: true
        include:
          - php: 5.5
          - php: 7.0
      before-install:
        - composer self-update
      install:
        - psql template1 -c 'CREATE EXTENSION "uuid-ossp";' -U postgres
        - phpenv config-add travis.php.ini
        - composer install
        - php bin/console doctrine:database:create --env=test
        - php bin/console doctrine:schema:create --env=test
        - php bin/console app:db-init --env=test
      script:
        - phpunit

    - language: node_js
      before_script:
        - cd frontend
      sudo: required
      dist: trusty
      node_js:
        - 6
      rvm:
        - 2.2.3
      cache:
        directories:
        - docs/vendor/bundle
        - node_modules
        - $HOME/.yarn-cache
      before_install:
        - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
        - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update -qq
        - sudo apt-get install -y -qq yarn
      install:
        - yarn install
      script:
        - npm run build

    - language: java
      before_script:
        - cd worker
      jdk:
        - oraclejdk8
      script:
        - mvn test

notifications:
  email: contact@luatix.org
