language: php
sudo: false

services:
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 7.0

before-install:
  - phpenv config-add travis.php.ini
  - composer self-update

install:
  - psql template1 -c 'CREATE EXTENSION "uuid-ossp";' -U postgres
  - composer --memory=4G install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console app:db-init --env=test

script:
  - phpunit

notifications:
  email: contact@luatix.org