language: node_js
sudo: required

cache:
  directories:
  - docs/vendor/bundle
  - node_modules
  - $HOME/.yarn-cache

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - yarn install

script:
  - npm run build

notifications:
  email: contact@luatix.org