sudo: required
dist: trusty
language: node_js

node_js:
- 6
rvm:
- 2.2.3

cache:
  directories:
  - docs/vendor/bundle
  - node_modules
  - $HOME/.yarn-cache

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - yarn install

script:
  - npm run build

notifications:
  email: contact@luatix.org