APIBundle\Entity\Subaudience:
    attributes:
        subaudience_id:
            groups: ['subaudience', 'audience', 'user', 'inject']
        subaudience_name:
            groups: ['subaudience']
        subaudience_exercise:
            groups: ['subaudience']
        subaudience_audience:
            groups: ['subaudience']
        subaudience_enabled:
            groups: ['subaudience']
        subaudience_users:
            groups: ['subaudience']
        subaudience_injects:
            groups: ['subaudience']