APIBundle\Entity\Parameter:
    attributes:
        parameter_id:
            groups: ['parameter']
        parameter_key:
            groups: ['parameter']
        parameter_value:
            groups: ['parameter']