users:
    type:     rest
    resource: APIBundle\Controller\UserController

groups:
    type:     rest
    resource: APIBundle\Controller\GroupController

groups_roles:
    type:     rest
    resource: APIBundle\Controller\Group\RoleController

groups_users:
    type:     rest
    resource: APIBundle\Controller\Group\UserController

tokens:
    type:     rest
    resource: APIBundle\Controller\TokenController

exercises:
    type:     rest
    resource: APIBundle\Controller\ExerciseController

exercises_events:
    type:     rest
    resource: APIBundle\Controller\Exercise\EventController