users:
    type:     rest
    resource: APIBundle\Controller\UserController

groups:
    type:     rest
    resource: APIBundle\Controller\GroupController

groups_grants:
    type:     rest
    resource: APIBundle\Controller\Group\GrantController

groups_users:
    type:     rest
    resource: APIBundle\Controller\Group\UserController

tokens:
    type:     rest
    resource: APIBundle\Controller\TokenController

organizations:
    type:     rest
    resource: APIBundle\Controller\OrganizationController

files:
    type:     rest
    resource: APIBundle\Controller\FileController

exercise_statuses:
    type:     rest
    resource: APIBundle\Controller\ExerciseStatusController

inject_statuses:
    type:     rest
    resource: APIBundle\Controller\InjectStatusController

exercises:
    type:     rest
    resource: APIBundle\Controller\ExerciseController

exercises_groups:
    type:     rest
    resource: APIBundle\Controller\Exercise\GroupController

exercises_audiences:
    type:     rest
    resource: APIBundle\Controller\Exercise\AudienceController

exercises_events:
    type:     rest
    resource: APIBundle\Controller\Exercise\EventController

exercises_events_incidents:
    type:     rest
    resource: APIBundle\Controller\Exercise\Event\IncidentController

exercises_events_incidents_injects:
    type:     rest
    resource: APIBundle\Controller\Exercise\Event\Incident\InjectController

exercises_events_incidents_outcomes:
    type:     rest
    resource: APIBundle\Controller\Exercise\Event\Incident\OutcomeController