doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api:
    resource: "routing_api.yml"
    prefix:   /api
    type:     rest

frontend:
    resource: "@FrontendBundle/Controller/DefaultController.php"
    prefix:   /
    type:     annotation

default:
    path: /{req}
    defaults: { _controller: 'FrontendBundle:Default:index' }
    requirements:
      req: ".+"