users:
    type:     rest
    resource: APIBundle\Controller\UserController

groups:
    type:     rest
    resource: APIBundle\Controller\GroupController

groups_grants:
    type:     rest
    resource: APIBundle\Controller\Group\GrantController

groups_users:
    type:     rest
    resource: APIBundle\Controller\Group\UserController

tokens:
    type:     rest
    resource: APIBundle\Controller\TokenController

exercises:
    type:     rest
    resource: APIBundle\Controller\ExerciseController

exercises_groups:
    type:     rest
    resource: APIBundle\Controller\Exercise\ExerciseGroupController

exercises_events:
    type:     rest
    resource: APIBundle\Controller\Exercise\ExerciseEventController