parameters:
    type:     rest
    resource: APIBundle\Controller\ParameterController

users:
    type:     rest
    resource: APIBundle\Controller\UserController

groups:
    type:     rest
    resource: APIBundle\Controller\GroupController

groups_grants:
    type:     rest
    resource: APIBundle\Controller\Group\GrantController

groups_users:
    type:     rest
    resource: APIBundle\Controller\Group\UserController

tokens:
    type:     rest
    resource: APIBundle\Controller\TokenController

organizations:
    type:     rest
    resource: APIBundle\Controller\OrganizationController

files:
    type:     rest
    resource: APIBundle\Controller\FileController

incident_types:
    type:     rest
    resource: APIBundle\Controller\IncidentTypeController

inject_types:
    type:     rest
    resource: APIBundle\Controller\InjectTypeController

inject_statuses:
    type:     rest
    resource: APIBundle\Controller\InjectStatusController

exercises:
    type:     rest
    resource: APIBundle\Controller\ExerciseController

exercises_comchecks:
    type:     rest
    resource: APIBundle\Controller\Exercise\ComcheckController

exercises_comchecks_statuses:
    type:     rest
    resource: APIBundle\Controller\Exercise\Comcheck\ComcheckStatusController

exercises_dryruns:
    type:     rest
    resource: APIBundle\Controller\Exercise\DryrunController

exercises_dryruns_injects:
    type:     rest
    resource: APIBundle\Controller\Exercise\Dryrun\DryinjectController

exercises_groups:
    type:     rest
    resource: APIBundle\Controller\Exercise\GroupController

exercises_objectives:
    type:     rest
    resource: APIBundle\Controller\Exercise\ObjectiveController

exercises_subobjectives:
    type:     rest
    resource: APIBundle\Controller\Exercise\SubobjectiveController

exercises_objectives_subobjectives:
    type:     rest
    resource: APIBundle\Controller\Exercise\Objective\SubobjectiveController

exercises_audiences:
    type:     rest
    resource: APIBundle\Controller\Exercise\AudienceController

exercises_audiences_users:
    type:     rest
    resource: APIBundle\Controller\Exercise\Audience\UserController

exercises_events:
    type:     rest
    resource: APIBundle\Controller\Exercise\EventController

exercises_incidents:
    type:     rest
    resource: APIBundle\Controller\Exercise\IncidentController

exercises_injects:
    type:     rest
    resource: APIBundle\Controller\Exercise\InjectController

exercises_events_incidents:
    type:     rest
    resource: APIBundle\Controller\Exercise\Event\IncidentController

exercises_events_injects:
    type:     rest
    resource: APIBundle\Controller\Exercise\Event\InjectController

exercises_event_incidents_injects:
    type:     rest
    resource: APIBundle\Controller\Exercise\Event\Incident\InjectController

exercises_event_incidents_injects_try:
    type:     rest
    resource: APIBundle\Controller\Exercise\Event\Incident\Inject\TryController

exercises_event_incidents_outcomes:
    type:     rest
    resource: APIBundle\Controller\Exercise\Event\Incident\OutcomeController

exercises_logs:
    type:     rest
    resource: APIBundle\Controller\Exercise\LogController

injects:
    type:     rest
    resource: APIBundle\Controller\InjectController

worker_status:
    type:     rest
    resource: APIBundle\Controller\WorkerStatusController