users:
    type:     rest
    resource: APIBundle\Controller\UserController

tokens:
    type:     rest
    resource: APIBundle\Controller\TokenController

exercises:
    type:     rest
    resource: APIBundle\Controller\ExerciseController

events:
    type:     rest
    resource: APIBundle\Controller\Exercise\EventController