frontend:
    resource: "@FrontendBundle/Controller/DefaultController.php"
    prefix:   /
    type:     annotation

doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api:
    resource: "routing_api.yml"
    prefix:   /api
    type:     rest