users:
    type:     rest
    resource: APIBundle\Controller\UserController

groups:
    type:     rest
    resource: APIBundle\Controller\GroupController

tokens:
    type:     rest
    resource: APIBundle\Controller\TokenController

exercises:
    type:     rest
    resource: APIBundle\Controller\ExerciseController

events:
    type:     rest
    resource: APIBundle\Controller\Exercise\EventController