users:
    type:     rest
    resource: APIBundle\Controller\UserController

events:
    type:     rest
    resource: APIBundle\Controller\Exercise\EventController

exercises:
    type:     rest
    resource: APIBundle\Controller\ExerciseController