# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    token_user_provider:
        class: APIBundle\Security\TokenUserProvider
        arguments: ["@token_repository", "@user_repository"]
        public:    false

    token_repository:
        class:   Doctrine\ORM\EntityManager
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["APIBundle:Token"]

    user_repository:
        class:   Doctrine\ORM\EntityManager
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["APIBundle:User"]

    token_authenticator:
        class:     APIBundle\Security\TokenAuthenticator
        arguments: ["@security.http_utils"]
        public:    false

    user_voter:
        class: APIBundle\Security\UserVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    exercise_voter:
        class: APIBundle\Security\ExerciseVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }