version: 2.1

jobs:
  build_platform:
    working_directory: ~/openex
    docker:
      - image: nikolaik/python-nodejs:python3.8-nodejs12
    steps:
      - run:
          command: apt-get update && apt-get install -y build-essential
      - checkout
      - run: 
          working_directory: ~/openex/openex-platform/openex-front
          command: yarn install
      - run:
          working_directory: ~/openex/openex-platform/openex-front
          command: yarn build
      - persist_to_workspace:
          root: ~/
          paths:
            - openex

  build_player:
    working_directory: ~/openex
    docker:
      - image: maven:3.6.3-openjdk-15
    steps:
      - attach_workspace:
          at: ~/
      - run: 
          working_directory: ~/openex/openex-player
          command: mvn install
      - persist_to_workspace:
          root: ~/
          paths:
            - openex

  package_rolling:
    working_directory: ~/openex
    docker:
      - image: chialab/php:7.4
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys
      - run: ssh-keyscan -H openex.io >> ~/.ssh/known_hosts
      - run:
          working_directory: ~/openex/openex-platform/openex-api
          command: php composer.phar install --no-progress --no-interaction
      - run: git config --global user.email "ci@openex.io" && git config --global user.name "OpenEx CircleCI"
      - run: git remote add openex ssh://git-9qdBths0@openex.io:/~/git-9qdBths0.git && git push --force openex master
      - run: mkdir release
      - run: cp -a ./openex-platform/openex-api release/openex
      - run: cp -a ./openex-platform/openex-front/build/index.html release/openex/templates/views/Default/index.html.twig
      - run: cp -a ./openex-platform/openex-front/build/static release/openex/public/
      - run: cp -a ./openex-platform/openex-front/build/images release/openex/public/
      - run: cp -a ./openex-platform/openex-front/build/ckeditor release/openex/public/
      - run: mkdir release/openex/player && cp -a ./openex-platform/openex-player/target/player-2.0.0.jar release/openex/player
      - run:
          working_directory: ~/openex/release
          command: tar -zcvf "openex-$(date '+%Y%m%d').tar.gz" openex
      - run: 
          working_directory: ~/openex/release
          command: scp "openex-$(date '+%Y%m%d').tar.gz" git-9qdBths0@openex.io:/dns/io/openex/releases/

  deploy_demo:
    working_directory: ~/openex
    docker:
      - image: chialab/php:7.4
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys
      - run: ssh-keyscan -H openex.io >> ~/.ssh/known_hosts
      - run: sudo apt-get update -qq && sudo apt install rsync
      - run: mkdir deploy
      - run: git config --global user.email "ci@openex.io" && git config --global user.name "OpenEx CircleCI"

  deploy_reference:
    working_directory: ~/opencti
    docker:
      - image: circleci/node:12.13.1-stretch
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys
      - run: ssh-keyscan -H opencti.io >> ~/.ssh/known_hosts    
      - run: sudo apt-get update -qq && sudo apt install rsync
      - run: mkdir -p deploy
      - run: git config --global user.email "ci@openex.io" && git config --global user.name "OpenEx CircleCI"

  docker_build:
    working_directory: ~/opencti
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker

  docker_build_rolling:
    working_directory: ~/opencti
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker

workflows:
  opencti:
    jobs:
      - build_platform:
          filters:
            tags:
              only: /.*/     
      - build_player:
          filters:
            tags:
              only: /.*/            
      - package_rolling:
          requires:
            - build_platform
            - build_player
          filters:
            branches:
              only:
                - master           
      - deploy_demo:
          requires:
            - build_platform
            - build_player
          filters:
            branches:
              only:
                - master
      - deploy_reference:
          requires:
            - build_platform
            - build_player
          filters:
            branches:
              only:
                - master
      - docker_build_rolling:
          requires:
            - build_platform
            - build_player
          filters:
            branches:
              only:
                - master
      - docker_build:
          requires:
            - build_platform
            - build_player
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              ignore: /.*/
