APIBundle\Entity\Audience:
    attributes:
        audience_id:
            groups: ['audience', 'user', 'inject']
        audience_name:
            groups: ['audience']
        audience_exercise:
            groups: ['audience']
        audience_users:
            groups: ['audience']
        audience_injects:
            groups: ['audience']