APIBundle\Entity\Audience:
    attributes:
        audience_id:
            groups: ['Audience', 'dryrun', 'user', 'inject', 'comcheck']
        audience_name:
            groups: ['Audience']
        audience_exercise:
            groups: ['Audience']
        audience_enabled:
            groups: ['Audience']
        audience_users:
            groups: ['Audience']
        audience_injects:
            groups: ['Audience']