APIBundle\Entity\Token:
    attributes:
        token_id:
            groups: ['token']
        token_value:
            groups: ['token']
        token_created_at:
            groups: ['token']
        token_user:
            groups: ['token']