APIBundle\Entity\Incident:
    attributes:
        incident_id:
            groups: ['incident']
        incident_type:
            groups: ['incident']
        incident_event:
            groups: ['incident']
        incident_title:
            groups: ['incident']
        incident_story:
            groups: ['incident']
        incident_injects:
            groups: ['incident']