APIBundle\Entity\Parameter:
    attributes:
        parameter_id:
            groups: ['parameter']
        parameter_name:
            groups: ['parameter']
        parameter_value:
            groups: ['parameter']