APIBundle\Entity\Organization:
    attributes:
        organization_id:
            groups: ['organization']
        organization_name:
            groups: ['organization']
        organization_descrption:
            groups: ['organization']
        organization_users:
            groups: ['organization']