APIBundle\Entity\Inject:
    attributes:
        inject_id:
            groups: ['inject', 'audience', 'incident']
        inject_title:
            groups: ['inject']
        inject_description:
            groups: ['inject']
        inject_content:
            groups: ['inject']
        inject_date:
            groups: ['inject']
        inject_type:
            groups: ['inject']
        inject_status:
            groups: ['inject']
        inject_incident:
            groups: ['inject']
        inject_audiences:
            groups: ['inject']
        inject_user:
            groups: ['inject']