APIBundle\Entity\Exercise:
    attributes:
        exercise_id:
            groups: ['exercise', 'audience']
        exercise_name:
            groups: ['exercise', 'audience']
        exercise_subtitle:
            groups: ['exercise']
        exercise_description:
            groups: ['exercise']
        exercise_start_date:
            groups: ['exercise']
        exercise_end_date:
            groups: ['exercise']
        exercise_image:
            groups: ['exercise']
        exercise_status:
            groups: ['exercise']