APIBundle\Entity\Inject:
    attributes:
        inject_id:
            groups: ['inject', 'audience', 'incident']
        inject_title:
            groups: ['inject', 'incident']
        inject_description:
            groups: ['inject', 'incident']
        inject_content:
            groups: ['inject']
        inject_date:
            groups: ['inject', 'incident']
        inject_sender:
            groups: ['inject', 'incident']
        inject_type:
            groups: ['inject']
        inject_status:
            groups: ['inject']
        inject_incident:
            groups: ['inject']