APIBundle\Entity\File:
    attributes:
        file_id:
            groups: ['file', 'exercise', 'inject']
        file_name:
            groups: ['file', 'exercise', 'inject']
        file_url:
            groups: ['file', 'exercise', 'inject']