APIBundle\Entity\Incident:
    attributes:
        incident_id:
            groups: ['incident', 'event', 'inject', 'subobjective']
        incident_type:
            groups: ['incident']
        incident_event:
            groups: ['incident']
        incident_title:
            groups: ['incident']
        incident_story:
            groups: ['incident']
        incident_weight:
            groups: ['incident']
        incident_injects:
            groups: ['incident']
        incident_subobjectives:
            groups: ['incident']
        incident_outcome:
            groups: ['incident']
        incident_exercise:
            groups: ['incident']