APIBundle\Entity\Objective:
    attributes:
        log_id:
            groups: ['log']
        log_title:
            groups: ['log']
        log_content:
            groups: ['log']
        log_date:
            groups: ['log']
        log_exercise:
            groups: ['log']
        log_user:
            groups: ['log']