APIBundle\Entity\Subobjective:
    attributes:
        subobjective_id:
            groups: ['subobjective', 'objective']
        subobjective_title:
            groups: ['subobjective']
        subobjective_description:
            groups: ['subobjective']
        subobjective_priority:
            groups: ['subobjective']
        subobjective_objective:
            groups: ['subobjective']