APIBundle\Entity\DryinjectStatus:
    attributes:
        status_id:
            groups: ['dryinjectStatus', 'dryinject']
        status_name:
            groups: ['dryinjectStatus', 'dryinject']
        status_message:
            groups: ['dryinjectStatus', 'dryinject']
        status_date:
            groups: ['dryinjectStatus', 'dryinject']