APIBundle\Entity\Organization:
    attributes:
        organization_id:
            groups: ['organization', 'user']
        organization_name:
            groups: ['organization', 'user']
        organization_description:
            groups: ['organization']
        organization_users:
            groups: ['organization']