APIBundle\Entity\Exercise:
    attributes:
        exercise_id:
            groups: ['exercise', 'dryrun', 'comcheck', 'audience', 'event', 'incident', 'objective', 'group', 'log']
        exercise_name:
            groups: ['exercise']
        exercise_subtitle:
            groups: ['exercise']
        exercise_description:
            groups: ['exercise']
        exercise_start_date:
            groups: ['exercise']
        exercise_end_date:
            groups: ['exercise']
        exercise_image:
            groups: ['exercise']
        exercise_status:
            groups: ['exercise']
        exercise_canceled:
            groups: ['exercise']