APIBundle\Entity\InjectStatus:
    attributes:
        status_id:
            groups: ['injectStatus', 'inject']
        status_name:
            groups: ['injectStatus', 'inject']
        status_message:
            groups: ['injectStatus', 'inject']
        status_date:
            groups: ['injectStatus', 'inject']
