APIBundle\Entity\User:
    attributes:
        user_id:
            groups: ['user', 'token']
        user_firstname:
            groups: ['user', 'token']
        user_lastname:
            groups: ['user', 'token']
        user_email:
            groups: ['user', 'token']
        user_phone:
            groups: ['user', 'token']
        user_organization:
            groups: ['user', 'token']
        user_gravatar:
            groups: ['user', 'token']
        user_admin:
            groups: ['user', 'token']
        user_groups:
            groups: ['user']
        user_audiences:
            groups: ['user']