AppBundle\Entity\User:
    attributes:
        user_id:
            groups: ['user', 'preference', 'token']
        user_firstname:
            groups: ['user', 'preference', 'token']
        user_lastname:
            groups: ['user', 'preference', 'token']
        user_email:
            groups: ['user', 'preference', 'token']
        user_preferences:
            groups: ['user']

AppBundle\Entity\Token:
    attributes:
        token_id:
            groups: ['token']
        token_value:
            groups: ['token']
        token_created_at:
            groups: ['token']
        token_user:
            groups: ['token']

APIBundle\Entity\Exercise:
    attributes:
        exercise_id:
            groups: ['exercise', 'event']
        exercise_name:
            groups: ['exercise', 'event']
        exercise_description:
            groups: ['exercise', 'event']
        exercise_start_date:
            groups: ['exercise', 'event']
        exercise_end_date:
            groups: ['exercise', 'event']
        exercise_status:
            groups: ['exercise', 'event']
        exercise_events:
            groups: ['exercise']

APIBundle\Entity\Event:
    attributes:
        event_id:
            groups: ['exercise', 'event']
        event_title:
            groups: ['exercise', 'event']
        event_description:
            groups: ['exercise', 'event']
        event_status:
            groups: ['exercise', 'event']
        event_exercise:
            groups: ['event']