APIBundle\Entity\Exercise:
    properties:
        exercise_name:
            - NotBlank: ~
            - Type: string
        exercise_description:
            - NotBlank: ~
            - Type: string
        exercise_start_date:
            - DateTime: ~
        exercise_end_date:
            - DateTime: ~
        exercise_status:
            - NotBlank: ~
            - Type: integer

APIBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: user_email
    properties:
        user_firstname:
            - NotBlank: ~
            - Type: string
        user_lastname:
            - NotBlank: ~
            - Type: string
        user_email:
            - NotBlank: ~
            - Email: ~

APIBundle\Entity\Event:
    properties:
        event_title:
            - NotBlank: ~
            - Type: string
        event_description:
            - NotBlank: ~
            - Type: string