APIBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: user_email
    properties:
        user_firstname:
            - NotBlank: ~
            - Type: string
        user_lastname:
            - NotBlank: ~
            - Type: string
        user_email:
            - NotBlank: ~
            - Email: ~
        user_plain_password:
            - NotBlank: { groups: [New, FullUpdate] }
            - Type: string
            - Length:
                min: 4
                max: 50

APIBundle\Entity\Group:
    properties:
        group_name:
            - NotBlank: ~
            - Type: string

APIBundle\Entity\Grant:
    properties:
        grant_name:
            - NotBlank: ~
            - Type: string

APIBundle\Entity\Credentials:
    properties:
        login:
            - NotBlank: ~
            - Type: string
        password:
            - NotBlank: ~
            - Type: string

APIBundle\Entity\Exercise:
    properties:
        exercise_name:
            - NotBlank: ~
            - Type: string
        exercise_subtitle:
            - NotBlank: ~
            - Type: string
        exercise_description:
            - NotBlank: ~
            - Type: string
        exercise_organizer:
            - NotBlank: ~
            - Type: string
        exercise_start_date:
            - DateTime: ~
            - NotBlank: ~
        exercise_end_date:
            - DateTime: ~
            - NotBlank: ~

APIBundle\Entity\Event:
    properties:
        event_title:
            - NotBlank: ~
            - Type: string
        event_description:
            - NotBlank: ~
            - Type: string

APIBundle\Entity\Incident:
    properties:
        incident_title:
            - NotBlank: ~
            - Type: string
        incident_story:
            - NotBlank: ~
            - Type: string
        incident_start_date:
            - DateTime: ~
        incident_end_date:
            - DateTime: ~
        incident_status:
            - NotBlank: ~
            - Type: integer