security:
  enable_authenticator_manager: true
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  password_hashers:
    App\Entity\User:
      algorithm: 'auto'
  providers:
    token_user_provider:
      id: token_user_provider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    doc:
      pattern: ^/api/doc
      stateless: true
      security: false

    auth:
      pattern: ^/api/auth
      stateless: true
      security: false

    comcheck:
      pattern: ^/api/comcheck
      stateless: true
      security: false

    parameters:
      pattern: ^/api/parameters
      stateless: true
      security: false

    api:
      pattern: ^/api
      stateless: true
      security: true
      custom_authenticators:
        - token_authenticator
      provider: token_user_provider

    frontend:
      pattern: ^/
      security: false

  access_control:
    - { path: '^/api/doc', roles: [] }
    - { path: '^/api/auth', roles: [] }
    - { path: '^/api/comcheck', roles: [] }
    - { path: '^/api', roles: [IS_AUTHENTICATED_FULLY] }
