comcheck_statuses:
  type: annotation
  resource: App\Controller\ComcheckStatusController

parameters:
  type: annotation
  resource: App\Controller\ParameterController

users:
  type: annotation
  resource: App\Controller\UserController

groups:
  type: annotation
  resource: App\Controller\GroupController

groups_grants:
  type: annotation
  resource: App\Controller\Group\GrantController

groups_users:
  type: annotation
  resource: App\Controller\Group\UserController

tokens:
  type: annotation
  resource: App\Controller\TokenController

organizations:
  type: annotation
  resource: App\Controller\OrganizationController

files:
  type: annotation
  resource: App\Controller\FileController

incident_types:
  type: annotation
  resource: App\Controller\IncidentTypeController

inject_types:
  type: annotation
  resource: App\Controller\InjectTypeController

inject_statuses:
  type: annotation
  resource: App\Controller\InjectStatusController

tests:
  type: annotation
  resource: App\Controller\TestsController

exercises:
  type: annotation
  resource: App\Controller\ExerciseController

exercises_export:
  type: annotation
  resource: App\Controller\Export\ExportExerciseController

exercises_tag:
  type: annotation
  resource: App\Controller\Exercise\Tag\TagController

exercises_document:
  type: annotation
  resource: App\Controller\Exercise\Tag\DocumentController

exercises_import:
  type: annotation
  resource: App\Controller\Import\ImportExerciseController

exercises_planificateur_audience:
  type: annotation
  resource: App\Controller\Exercise\Planificateur\AudiencePlanificateurController

exercises_planificateur_event:
  type: annotation
  resource: App\Controller\Exercise\Planificateur\EventPlanificateurController

exercises_statistics:
  type: annotation
  resource: App\Controller\Exercise\StatisticController

exercises_comchecks:
  type: annotation
  resource: App\Controller\Exercise\ComcheckController

exercises_comchecks_statuses:
  type: annotation
  resource: App\Controller\Exercise\Comcheck\ComcheckStatusController

exercises_dryruns:
  type: annotation
  resource: App\Controller\Exercise\DryrunController

exercises_dryruns_injects:
  type: annotation
  resource: App\Controller\Exercise\Dryrun\DryinjectController

exercises_groups:
  type: annotation
  resource: App\Controller\Exercise\GroupController

exercises_objectives:
  type: annotation
  resource: App\Controller\Exercise\ObjectiveController

exercises_subobjectives:
  type: annotation
  resource: App\Controller\Exercise\SubobjectiveController

exercises_objectives_subobjectives:
  type: annotation
  resource: App\Controller\Exercise\Objective\SubobjectiveController

exercises_audiences:
  type: annotation
  resource: App\Controller\Exercise\AudienceController

exercises_audiences_users:
  type: annotation
  resource: App\Controller\Exercise\Audience\UserController

exercises_audiences_subaudiences:
  type: annotation
  resource: App\Controller\Exercise\Audience\SubaudienceController

exercises_audiences_subaudiences_users:
  type: annotation
  resource: App\Controller\Exercise\Audience\Subaudience\UserController

exercises_subaudiences:
  type: annotation
  resource: App\Controller\Exercise\SubaudienceController

exercises_events:
  type: annotation
  resource: App\Controller\Exercise\EventController

exercises_incidents:
  type: annotation
  resource: App\Controller\Exercise\IncidentController

exercises_injects:
  type: annotation
  resource: App\Controller\Exercise\InjectController

exercises_change_duration:
  type: annotation
  resource: App\Controller\Exercise\ChangeDuration\ChangeDurationController

exercises_events_incidents:
  type: annotation
  resource: App\Controller\Exercise\Event\IncidentController

exercises_events_injects:
  type: annotation
  resource: App\Controller\Exercise\Event\InjectController

exercises_event_incidents_injects:
  type: annotation
  resource: App\Controller\Exercise\Event\Incident\InjectController

exercises_event_incidents_injects_try:
  type: annotation
  resource: App\Controller\Exercise\Event\Incident\Inject\TryController

exercises_event_incidents_outcomes:
  type: annotation
  resource: App\Controller\Exercise\Event\Incident\OutcomeController

exercises_logs:
  type: annotation
  resource: App\Controller\Exercise\LogController

injects:
  type: annotation
  resource: App\Controller\InjectController

worker_status:
  type: annotation
  resource: App\Controller\WorkerStatusController
