app.swagger:
  path: '/api/doc.json'
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
  path: '/api/doc'
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api:
  resource: 'routes/routing_api.yml'
  type: annotation

defaultReq:
  path: '/{req}'
  defaults: { _controller: App\Controller\DefaultController::indexAction }
  requirements:
    req: ".+"

default:
  path: '/'
  defaults: { _controller: App\Controller\DefaultController::indexAction }
