App\Entity\Objective:
  attributes:
    objective_id:
      groups: [ 'objective', 'subobjective' ]
    objective_title:
      groups: [ 'objective' ]
    objective_description:
      groups: [ 'objective' ]
    objective_priority:
      groups: [ 'objective' ]
    objective_exercise:
      groups: [ 'objective' ]
    objective_subobjectives:
      groups: [ 'objective' ]
    user_can_update:
      groups: [ 'objective' ]
    user_can_delete:
      groups: [ 'objective' ]