App\Entity\Token:
  attributes:
    token_id:
      groups: [ 'token', 'user' ]
    token_value:
      groups: [ 'token', 'user' ]
    token_created_at:
      groups: [ 'token' ]
    token_user:
      groups: [ 'token' ]