App\Entity\Exercise:
    attributes:
        exercise_id:
            groups: ['exercise', 'dryrun', 'comcheck', 'audience', 'event', 'incident', 'objective', 'group', 'log']
        exercise_name:
            groups: ['exercise']
        exercise_subtitle:
            groups: ['exercise']
        exercise_description:
            groups: ['exercise']
        exercise_start_date:
            groups: ['exercise']
        exercise_end_date:
            groups: ['exercise']
        exercise_image:
            groups: ['exercise']
        exercise_status:
            groups: ['exercise']
        exercise_owner_id:
            groups: ['exercise']
        exercise_canceled:
            groups: ['exercise']
        exercise_type:
            groups: ['exercise']
        exercise_message_header:
            groups: ['exercise']
        exercise_message_footer:
            groups: ['exercise']
        exercise_animation_group:
            groups: ['exercise']
        exercise_mail_expediteur:
            groups: ['exercise']            
        user_can_update:
            groups: ['exercise']
        user_can_delete:
            groups: ['exercise']
