App\Entity\Audience:
  attributes:
    audience_id:
      groups: [ 'audience', 'subaudience', 'inject', 'comcheck' ]
    audience_name:
      groups: [ 'audience' ]
    audience_exercise:
      groups: [ 'audience' ]
    audience_enabled:
      groups: [ 'audience' ]
    audience_injects:
      groups: [ 'audience' ]
    audience_subaudiences:
      groups: [ 'audience' ]
    audience_users_number:
      groups: [ 'audience' ]
    user_can_update:
      groups: [ 'audience' ]
    user_can_delete:
      groups: [ 'audience' ]