APIBundle\Entity\Exercise:
    exclusion_policy: none
    properties:
        exercise_id:
            groups: ['exercise']
        exercise_name:
            groups: ['exercise']
        exercise_subtitle:
            groups: ['exercise']
        exercise_description:
            groups: ['exercise']
        exercise_organizer:
            groups: ['exercise']
        exercise_start_date:
            groups: ['exercise']
        exercise_end_date:
            groups: ['exercise']
        exercise_status:
            groups: ['exercise']