APIBundle\Entity\Group:
    exclusion_policy: none
    properties:
        group_id:
            groups: ['group', 'user', 'role']
        group_name:
            groups: ['group', 'user', 'role']
        group_users:
            groups: ['group', 'role']
        group_roles:
            groups: ['group', 'user']