APIBundle\Entity\User:
    exclusion_policy: none
    properties:
        user_id:
            groups: ['user', 'group']
        user_firstname:
            groups: ['user', 'group']
        user_lastname:
            groups: ['user', 'group']
        user_email:
            groups: ['user', 'group']
        user_groups:
            groups: ['user']