APIBundle\Entity\Inject:
    exclusion_policy: none
    properties:
        inject_id:
            groups: ['inject']
        inject_title:
            groups: ['inject']
        inject_description:
            groups: ['inject']
        inject_content:
            groups: ['inject']
        inject_date:
            groups: ['inject']
        inject_sender:
            groups: ['inject']
        inject_status:
            groups: ['inject']