APIBundle\Entity\Grant:
    exclusion_policy: none
    properties:
        grant_id:
            groups: ['grant']
        grant_group:
            groups: ['grant']
        grant_exercise:
            groups: ['grant']
        grant_name:
            groups: ['grant']