parameters:
    type:     rest
    resource: App\Controller\ParameterController

users:
    type:     rest
    resource: App\Controller\UserController

groups:
    type:     rest
    resource: App\Controller\GroupController

groups_grants:
    type:     rest
    resource: App\Controller\Group\GrantController

groups_users:
    type:     rest
    resource: App\Controller\Group\UserController

tokens:
    type:     rest
    resource: App\Controller\TokenController

organizations:
    type:     rest
    resource: App\Controller\OrganizationController

files:
    type:     rest
    resource: App\Controller\FileController

incident_types:
    type:     rest
    resource: App\Controller\IncidentTypeController

inject_types:
    type:     rest
    resource: App\Controller\InjectTypeController

inject_statuses:
    type:     rest
    resource: App\Controller\InjectStatusController

tests:
    type:     rest
    resource: App\Controller\TestsController

exercises:
    type:     rest
    resource: App\Controller\ExerciseController

exercises_export:
    type:     rest
    resource: App\Controller\Export\ExportExerciseController

exercises_tag:
    type:     rest
    resource: App\Controller\Exercise\Tag\TagController

exercises_document:
    type:     rest
    resource: App\Controller\Exercise\Tag\DocumentController

exercises_import:
    type:     rest
    resource: App\Controller\Import\ImportExerciseController

exercises_planificateur_audience:
    type:     rest
    resource: App\Controller\Exercise\Planificateur\AudiencePlanificateurController

exercises_planificateur_event:
    type:     rest
    resource: App\Controller\Exercise\Planificateur\EventPlanificateurController

exercises_statistics:
    type:     rest
    resource: App\Controller\Exercise\StatisticController

exercises_comchecks:
    type:     rest
    resource: App\Controller\Exercise\ComcheckController

exercises_comchecks_statuses:
    type:     rest
    resource: App\Controller\Exercise\Comcheck\ComcheckStatusController

exercises_dryruns:
    type:     rest
    resource: App\Controller\Exercise\DryrunController

exercises_dryruns_injects:
    type:     rest
    resource: App\Controller\Exercise\Dryrun\DryinjectController

exercises_groups:
    type:     rest
    resource: App\Controller\Exercise\GroupController

exercises_objectives:
    type:     rest
    resource: App\Controller\Exercise\ObjectiveController

exercises_subobjectives:
    type:     rest
    resource: App\Controller\Exercise\SubobjectiveController

exercises_objectives_subobjectives:
    type:     rest
    resource: App\Controller\Exercise\Objective\SubobjectiveController

exercises_audiences:
    type:     rest
    resource: App\Controller\Exercise\AudienceController

exercises_audiences_users:
    type:     rest
    resource: App\Controller\Exercise\Audience\UserController

exercises_audiences_subaudiences:
    type:     rest
    resource: App\Controller\Exercise\Audience\SubaudienceController

exercises_audiences_subaudiences_users:
    type:     rest
    resource: App\Controller\Exercise\Audience\Subaudience\UserController

exercises_subaudiences:
    type:     rest
    resource: App\Controller\Exercise\SubaudienceController

exercises_events:
    type:     rest
    resource: App\Controller\Exercise\EventController

exercises_incidents:
    type:     rest
    resource: App\Controller\Exercise\IncidentController

exercises_injects:
    type:     rest
    resource: App\Controller\Exercise\InjectController

exercises_change_duration:
    type:     rest
    resource: App\Controller\Exercise\ChangeDuration\ChangeDurationController

exercises_events_incidents:
    type:     rest
    resource: App\Controller\Exercise\Event\IncidentController

exercises_events_injects:
    type:     rest
    resource: App\Controller\Exercise\Event\InjectController

exercises_event_incidents_injects:
    type:     rest
    resource: App\Controller\Exercise\Event\Incident\InjectController

exercises_event_incidents_injects_try:
    type:     rest
    resource: App\Controller\Exercise\Event\Incident\Inject\TryController

exercises_event_incidents_outcomes:
    type:     rest
    resource: App\Controller\Exercise\Event\Incident\OutcomeController

exercises_logs:
    type:     rest
    resource: App\Controller\Exercise\LogController

injects:
    type:     rest
    resource: App\Controller\InjectController

worker_status:
    type:     rest
    resource: App\Controller\WorkerStatusController
