name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Build and Push the Docker image
      run: |
          echo "dckr_pat_CwecW5U-RCs39bwcXNx1MfdfegE" | docker login -u "pantaleone" --password-stdin docker.io
          docker build . --file Dockerfile --tag latest
          docker push docker.io/pantaleone/testopenex:latest
